spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temporal-tests
    username: test_user
    password: test_pass
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  cache:
    cache-names: productsAvailableById

logging:
  level:
    root: INFO
    ru.dmkuranov.temporaltests.core: INFO
